"""Base agent implementation for ARAG."""

import json
import re
from typing import Any, Dict, List, Optional

_THINK_RE = re.compile(r'<think>.*?</think>', re.DOTALL)


def _strip_thinking(text: str) -> str:
    """Remove <think>...</think> blocks generated by thinking-mode LLMs."""
    return _THINK_RE.sub('', str(text)).strip()


def _extract_finish_answer(text: str) -> Optional[str]:
    """Extract answer from finish() written as plain text instead of a tool call.

    Handles patterns:
      finish({"answer": "X", ...})          — JSON dict
      finish(answer="X", ...)               — Python kwargs
      finish("X")                           — positional string
      {"name": "finish", "arguments": ...}  — vLLM serialised tool call
    Returns the extracted answer string, or None if no finish() found.
    """
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL).strip()

    if 'finish' not in text and '"finish"' not in text:
        return None

    # Pattern 1: JSON dict style — finish({"answer": "X", ...})
    m = re.search(
        r'finish\s*\(\s*\{[^)]*?"answer"\s*:\s*"((?:[^"\\]|\\.)*)"',
        text, re.DOTALL,
    )
    if m:
        return m.group(1).replace('\\"', '"')

    # Pattern 2: Python-kwargs style — finish(answer="X", ...)  or finish(answer='X', ...)
    m = re.search(r'finish\s*\(\s*answer\s*=\s*["\']([^"\']*)["\']', text)
    if m:
        return m.group(1)

    # Pattern 3: Positional string — finish("X") or finish('X')
    m = re.search(r'finish\s*\(\s*["\']([^"\']{1,300})["\']', text)
    if m:
        return m.group(1)

    # Pattern 4: vLLM serialised tool call — {"name":"finish","arguments":{"answer":"X"}}
    m = re.search(r'"name"\s*:\s*"finish"[^}]*?"arguments"\s*:\s*(\{[^}]+\})', text, re.DOTALL)
    if m:
        try:
            args = json.loads(m.group(1))
            return args.get('answer', '')
        except json.JSONDecodeError:
            pass
        m2 = re.search(r'"answer"\s*:\s*"([^"]*)"', m.group(1))
        if m2:
            return m2.group(1)

    # Pattern 5: loose JSON with answer key anywhere in text
    m = re.search(r'"answer"\s*:\s*"((?:[^"\\]|\\.){1,300})"', text)
    if m:
        return m.group(1).replace('\\"', '"')

    return None


import tiktoken

from arag.core.context import AgentContext
from arag.core.llm import LLMClient
from arag.tools.registry import ToolRegistry


_RETRY_PROMPT = (
    "You must call a tool. Do not write tool calls as text. "
    "If you have found the answer, call the **finish** tool now with your answer. "
    "If you need more information, call keyword_search or semantic_search."
)

_FORCE_PROMPT = (
    "You have reached the search limit. "
    "Based on everything you have found so far, call the **finish** tool with your best answer. "
    "Do NOT write any text — only make a finish tool call."
)


class BaseAgent:
    """Base agent with tool calling capabilities."""

    def __init__(
        self,
        llm_client: LLMClient,
        tools: ToolRegistry,
        system_prompt: str = None,
        max_loops: int = 10,
        max_token_budget: int = 128000,
        verbose: bool = False,
    ):
        self.llm = llm_client
        self.tools = tools
        self.system_prompt = system_prompt or "You are a helpful assistant."
        self.max_loops = max_loops
        self.max_token_budget = max_token_budget
        self.verbose = verbose
        self.tokenizer = tiktoken.encoding_for_model("gpt-4o")

    def _calculate_message_tokens(self, messages: List[Dict[str, Any]]) -> int:
        total = len(self.tokenizer.encode(self.system_prompt))
        for msg in messages:
            content = msg.get("content", "")
            if content:
                total += len(self.tokenizer.encode(str(content)))
        return total

    def _force_finish(self, messages: List[Dict[str, Any]], context: AgentContext,
                      total_cost: float, tool_schemas: list) -> tuple:
        """Force the model to call finish() via tool call."""
        messages.append({"role": "user", "content": _FORCE_PROMPT})
        try:
            response = self.llm.chat(messages=messages, tools=tool_schemas, temperature=0.0)
            total_cost += response["cost"]
            message = response["message"]
            messages.append(message)

            tool_calls = message.get("tool_calls") or []
            for tc in tool_calls:
                if tc["function"]["name"] == "finish":
                    try:
                        args = json.loads(tc["function"]["arguments"])
                    except json.JSONDecodeError:
                        args = {}
                    answer = _strip_thinking(args.get("answer", ""))
                    return answer, total_cost

            # Still no tool call — extract from text
            content = _strip_thinking(message.get("content", ""))
            extracted = _extract_finish_answer(content)
            return (extracted or content or ""), total_cost

        except Exception as e:
            if self.verbose:
                print(f"Error forcing finish: {e}")
            return "", total_cost

    def run(self, query: str, context: Optional[AgentContext] = None) -> Dict[str, Any]:
        context = context or AgentContext()
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user", "content": query},
        ]

        trajectory = []
        total_cost = 0.0
        loop_count = 0
        tool_schemas = self.tools.get_all_schemas()

        if self.verbose:
            print(f"\n{'='*60}")
            print(f"Question: {query}")
            print(f"{'='*60}\n")

        for loop_idx in range(self.max_loops):
            loop_count = loop_idx + 1

            current_tokens = self._calculate_message_tokens(messages)
            if current_tokens > self.max_token_budget:
                if self.verbose:
                    print(f"Token budget exceeded ({current_tokens}), forcing finish...")
                final_answer, total_cost = self._force_finish(
                    messages, context, total_cost, tool_schemas
                )
                return {
                    "answer": final_answer,
                    "trajectory": trajectory,
                    "total_cost": total_cost,
                    "loops": loop_count,
                    "token_budget_exceeded": True,
                    **context.get_summary(),
                }

            if self.verbose:
                print(f"Loop {loop_count}/{self.max_loops} (Tokens: {current_tokens}/{self.max_token_budget})")

            try:
                response = self.llm.chat(messages=messages, tools=tool_schemas)
            except Exception as e:
                if self.verbose:
                    print(f"LLM error: {e}")
                break

            total_cost += response["cost"]
            message = response["message"]
            messages.append(message)

            if self.verbose and message.get("content"):
                print(f"Assistant: {message['content'][:200]}...")

            tool_calls = message.get("tool_calls")

            if not tool_calls:
                content = _strip_thinking(message.get("content", ""))

                # Check if model wrote finish() as plain text instead of tool call
                extracted = _extract_finish_answer(content)
                if extracted is not None:
                    if self.verbose:
                        print(f"Recovered finish() from plain text: '{extracted[:80]}'")
                    return {
                        "answer": extracted,
                        "trajectory": trajectory,
                        "total_cost": total_cost,
                        "loops": loop_count,
                        **context.get_summary(),
                    }

                # Model gave a plain-text response without tools — re-prompt once
                if loop_idx < self.max_loops - 1:
                    if self.verbose:
                        print(f"No tool call — re-prompting to use tools...")
                    messages.append({"role": "user", "content": _RETRY_PROMPT})
                    continue

                # Last loop — return whatever the model said
                return {
                    "answer": content,
                    "trajectory": trajectory,
                    "total_cost": total_cost,
                    "loops": loop_count,
                    **context.get_summary(),
                }

            # Execute tool calls
            for tc in tool_calls:
                func_name = tc["function"]["name"]
                try:
                    func_args = json.loads(tc["function"]["arguments"])
                except json.JSONDecodeError:
                    func_args = {}

                if self.verbose:
                    print(f"Tool: {func_name}")
                    print(f"  Args: {func_args}")

                try:
                    tool_result, tool_log = self.tools.execute(func_name, context, **func_args)
                except Exception as e:
                    tool_result = f"Error executing tool: {str(e)}"
                    tool_log = {"retrieved_tokens": 0, "error": str(e)}

                if self.verbose:
                    output_preview = tool_result[:300] + "..." if len(tool_result) > 300 else tool_result
                    print(f"  Result: {output_preview}")
                    if tool_log.get("retrieved_tokens", 0) > 0:
                        print(f"  Tokens: {tool_log['retrieved_tokens']}")
                    print()

                messages.append({
                    "role": "tool",
                    "tool_call_id": tc["id"],
                    "content": tool_result,
                })

                traj_entry = {
                    "loop": loop_count,
                    "tool_name": func_name,
                    "arguments": func_args,
                    "tool_result": tool_result,
                    **tool_log,
                }
                trajectory.append(traj_entry)

                if func_name == "finish":
                    return {
                        "answer": _strip_thinking(func_args.get("answer", tool_result)),
                        "trajectory": trajectory,
                        "total_cost": total_cost,
                        "loops": loop_count,
                        "confidence": tool_log.get("confidence", 1.0),
                        "supporting_chunk_ids": tool_log.get("supporting_chunk_ids", []),
                        **context.get_summary(),
                    }

        # Max loops reached — force finish via tool call
        if self.verbose:
            print(f"Max loops reached ({self.max_loops}), forcing finish...")
        final_answer, total_cost = self._force_finish(
            messages, context, total_cost, tool_schemas
        )
        return {
            "answer": final_answer,
            "trajectory": trajectory,
            "total_cost": total_cost,
            "loops": loop_count,
            "max_loops_exceeded": True,
            **context.get_summary(),
        }
