#!/bin/bash
#SBATCH --job-name=ar-no_b-800
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=02:00:00
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/ar1k_no_branch_800_%j.out

source /projects/prjs1800/venvs/arag-venv/bin/activate
export PYTHONPATH=/projects/prjs1800/msc-thesis/07-daes/dllm:$PYTHONPATH
export HF_HOME=/projects/prjs1800/.cache/huggingface
export TRANSFORMERS_CACHE=/projects/prjs1800/.cache/huggingface

python -u /projects/prjs1800/msc-thesis/07-daes/src/daes/ablation_ar_single_mode.py     --mode no_branch --start_idx 800 --end_idx 900
