#!/bin/bash
#SBATCH --job-name=build-all-idx
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=80G
#SBATCH --time=02:00:00
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/build_all_indices_%j.out

source /projects/prjs1800/venvs/nvembed-venv/bin/activate
export HF_HOME=/projects/prjs1800/.cache/huggingface

python -u /projects/prjs1800/msc-thesis/07-daes/src/daes/build_all_indices.py
