#!/bin/bash
#SBATCH --job-name=build-idx
#SBATCH --partition=gpu_h100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=00:30:00
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/build_index_%j.out

source /projects/prjs1800/venvs/arag-venv/bin/activate
export HF_HOME=/projects/prjs1800/.cache/huggingface

python -u /projects/prjs1800/msc-thesis/07-daes/src/daes/build_musique_index.py
