#!/bin/bash
#SBATCH --job-name=dgmqr_pool_fewshot_2wikimultihop_500
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/dgmqr_pool_fewshot_2wikimultihop_500_%j.out
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=64G
#SBATCH --time=02:00:00

source /projects/prjs1800/venvs/arag-venv/bin/activate
export PYTHONPATH=/projects/prjs1800/msc-thesis/07-daes/dllm:$PYTHONPATH
export HF_HOME=/projects/prjs1800/.cache/huggingface

cd /projects/prjs1800/msc-thesis/07-daes
python src/daes/dgmqr.py --dataset 2wikimultihop --mode pool --few_shot --start_idx 500 --end_idx 600
