#!/bin/bash
#SBATCH --job-name=judge_musique
#SBATCH --partition=cbuild
#SBATCH --time=04:00:00
#SBATCH --mem=4G
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/llm_judge/judge_musique_%j.out

module load 2024
module load Python/3.11.5-GCCcore-13.2.0
source /projects/prjs1800/venvs/arag-venv/bin/activate

export PYTHONPATH=/projects/prjs1800/msc-thesis/07-daes/src/daes
cd /projects/prjs1800/msc-thesis/07-daes

python -u src/daes/llm_judge_eval.py --dataset musique --model gpt-4.1-mini
