#!/bin/bash
#SBATCH --job-name=lla-val-10q
#SBATCH --partition=gpu_a100
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=8
#SBATCH --mem=80G
#SBATCH --time=00:30:00
#SBATCH --output=/projects/prjs1800/msc-thesis/07-daes/results/llada/llada_validate_10q_%j.out

source /projects/prjs1800/venvs/arag-venv/bin/activate
export PYTHONPATH=/projects/prjs1800/msc-thesis/07-daes/dllm:/projects/prjs1800/msc-thesis/07-daes/src/daes
export HF_HOME=/projects/prjs1800/.cache/huggingface
export TRANSFORMERS_CACHE=/projects/prjs1800/.cache/huggingface
cd /projects/prjs1800/msc-thesis/07-daes

python -u src/daes/llada_10q_test.py
